### ISSUE TITLE
Recycling Maschine

### ISSUE THREAD

**Issue by joe7575** [joe7575/techage_feature_requests#20]
Des weiteren würde ich mir einen Recycling Klotz wünschen.  Darin kann man nicht benötigte Funktionsklötze aus TA4 wieder in die  Ausgangsmaterialien zerlegen. Recycling ist doch im Grunde nichts anderes als eine Mühle, nur  das je nach zugeführten Block mehrere Ausgabeblöcke erfolgen

**Comment by acmgit** [comment]
Könnte man da nicht mehr Blöcke in ein paar Rezeptteile zerlegen?

**Comment by joe7575** [comment]
Schon, es muss aber sichergestellt sein, dass das nicht zum Vervielfältigen von Items genutzt werden kann. Der Output sollte auch kleiner sein als der ursprüngliche Input. Oder es muss viel Energie kosten, aber welche Rezepte sind dann wie zu gewichten.
Auch sollten nicht alle Blöcke recycelt werden können. Bspw. Beton Blöcke wieder in Wasser, Zement, Sand und Stahlmatten zu zerlegen kommt mir schon seltsam vor.
Alles nicht so einfach...

**Comment by acmgit** [comment]
Natürlich sollte weniger als das benötigte Rezept dabei rauskommen, Schwund ist bei Recycling immer da.

* Anzahl der Materialien checken und nur zufällig einen kleinen Teil dabei zurück geben.
* Eine Liste aller recyclebaren Gegenstände führen mit dem festen Output dabei.
* Eine API dafür liefern, daß jeder Mod zusätzliche Gegenstände einfach registrieren kann.

Ich denke, man sollte da nicht so kompliziert denken ;-).
Greetings, Clyde.

**Comment by joe7575** [comment]
Dein Vorschlag trifft es schon ziemlich genau :+1: 
Dann mach mal :D

**Comment by acmgit** [comment]
Lass ich mir nicht zweimal sagen ;-).

```lua
 function recycler.work(to_recycle)
 local mats = nil
     if(recycler.item[to_recycle]) then
        mats = recycler.item[to_recycle]         
                                   
     end
    
     return mats
    
 end
```
Das komplette Beispiel inkl. Registrierfunktion findest du bei [Recycler Beispiel](https://github.com/acmgit/MT_Recycler).

Greetings, Clyde.

P.S.: Keine Ahnung warum die Code-Tags nicht funktionieren, aber du hast ja auch den gesamten Code.
Edit: So gehen die Code-Tags

**Comment by PapaSmok** [comment]
Also ganz ehrlich - dafuer nutzt man den grinder - und somit einfache
rezepte - hauste die muehle in den grinder kommen eben etwas stah und ein
paar stoecker hinten raus. Sehe nicht das Problem, welches ihr habt.

Am So., 3. Jan. 2021 um 18:05 Uhr schrieb acmgit <notifications@github.com>:

**Comment by acmgit** [comment]
Ich denke, weil ein Grinder alles in Staub zermahlt, mM. nach würden da hinten etwas Sägespäne u. Eisenpulver raus kommen.
Recycling selbst, wäre aber, wie Joe schon schrieb ein sehr energiehungriger Job.
