### ISSUE TITLE
Leitungen verputzen

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage_feature_requests#33]
Schön wäre das Feature, daß Rohrleitungen wie Stromleitungen auch verputzbar wären.
Man könnte dann auch kompakter bauen.

**Comment by joe7575** [comment]
Ist im Moment nicht möglich, da der ganze Software-Unterbau nicht dafür geeignet ist, die dann verschiedenen Leitungs-Typen zu unterschieden. Dies erfordert größere Umbaumaßnahmen. Ist aber nicht unmöglich...

**Comment by Thomas--S** [comment]
TA 3 Junction Pipes lassen sich doch aber bereits verputzen, oder?

**Comment by joe7575** [comment]
Also nicht von mir. Es gibt einen "Wanddurchbruchsblock", der wird als Pipe-Block akzeptiert. Mehr aber nicht.
Ich bin aber dabei, tubelib2 aufzubohren, so dass hidden nodes generell unterstützt werden, das dauert aber noch...

**Comment by Thomas--S** [comment]
https://github.com/joe7575/techage/blob/c2438a9ba4e2d3210f4a3eabd3240d6994b8b586/liquids/liquid_pipe.lua#L154

**Comment by joe7575** [comment]
Das ist ein copy/paste Fehler. Damit dies geht, müssen auch Methoden in tubelib2 überladen werden: https://github.com/joe7575/techage/blob/master/power/electric_cable.lua#L58
Aber bitte keinen PR dazu machen :), ich will das Problem "an der Wurzel" lösen

**Comment by joe7575** [comment]
Technisch (dank `networks`) geht das zwar jetzt für alle Typen von `tubelib2` Verbindungen, aber nachträglich ist das nicht mehr machbar. Für neue Kabel/Röhren wäre dies aber kein Problem
