### ISSUE TITLE
TA3 Schalter

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage_feature_requests#34]
Diesen Schalter auch für das Terminal nutzbar machen.
Damit lassen sich dann komplexere Anlagen mit einem Knopfdruck ein bzw. ausschalten.

Oder beim Befehl cmd mehrere Blocknummern unterstützen und damit komplexere Anlagen ein bzw. ausschalten.

**Comment by joe7575** [comment]
Welches Terminal? Es gibt 3 verschiedene. Meinst du das TA3 Terminal? Aber alle 3 Terminals machen von sich aus nichts. Wenn du da einen Schalter anschließt, könntest du den maximal über cmd abfragen.

Das Problem mit mehrere Blocknummern kannst du mit dem TA3 Wiederholer / repeater lösen.

**Comment by acmgit** [comment]
Über das TA3-Terminal ist es nicht möglich, diesen Block anzusprechen.
Wo wir gerade dabei sind: Was genau ist der Unterschied zwischen dem Schalter und den Repeater, ausser daß der Repeater von sich aus kein Signal senden kann?
Ich meine: 
Dem Schalter kann man mit mehreren Blöcken "programmieren", das klappt auch recht gut.
Der Repeater macht jetzt, wann man ihn mit dem Schalter koppelt genau das gleiche.
Da bin ich aus der Beschreibung heraus nicht ganz dahinter gekommen.

**Comment by joe7575** [comment]
> Was genau ist der Unterschied zwischen dem Schalter und den Repeater, ausser daß der Repeater von sich aus kein Signal senden kann?

Genau das, der Repeater gibt empfangene Signale weiter. Dein Wunsch war, mit dem "...Befehl cmd mehrere Blocknummern unterstützen..." Wenn du den Repeater dazwischenschaltest, hast du genau dies.

Der Schalter ist auf Signalebene ein reiner Sender. Der Repeater ist Sender und Empfänger, da er Signale weitergibt.

Wenn ich dich jetzt richtig verstanden habe, soll der Schalter ein Signal vom Terminal empfangen und dieses wie der Repeater weitergeben, richtig?

**Comment by acmgit** [comment]
Richtig, oder eben in diesem Fall würde das wohl eher der Repeater übernehmen, würde mehr Sinn machen.
