### ISSUE TITLE
TA4-Schieber

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage_feature_requests#35]
Der TA4-Schieber könnte als upgrade zum TA3-Schieber komplette Stacks schieben.

**Comment by joe7575** [comment]
Aber dann stauen sich die Items wieder an Verteilern oder spätestens an der nächsten Maschine. Mehr Verarbeitungsleistung halte ich nicht für passend.

**Comment by acmgit** [comment]
Gutes Argument, ich schließe dann diesen Request wieder ;-).
