### ISSUE TITLE
der spieler solte erfindungen    endecken koennen

### ISSUE THREAD

**Issue by celleron56** [joe7575/techage_feature_requests#51]
der spieler solte zeitgemaese erfindungen machen oder ""wiedererfinden""""" koennen meine idee waere der spieler  baut 4 neue bloecke im umkreis von 5 metern oder so auf (wie beim pdp13) den erfindungs tisch den blueprint tisch und die werkzeugbox und die werkbank   dann kann er mit den blueprint tisch blueprints endekt bzw """wiedererfindet"""" die blueprints kann er dan bei den erfindungs tisch benutzten und dan sieht er eine liste von teilen die er mit der werkbank machen muss um die erfindung zu erfinden wen er das getan hat kann er  die erfindung mit den erfindungstisch machen wobei es eine chance gibt 1\3 das die erfindung nichts wirkt wen er die "erfunden" hat  kann er die in ein buch notieren und dan die immer wider mit der werkbank machen zum beispiel  ein computer der klein ist  , router , microscope , cars , flugzeuge , radios ,cameras,  waseermuellen ,  usw

**Comment by joe7575** [comment]
Ja, soll es geben. Wird für TA5 Items benötigt

**Comment by joe7575** [comment]
Dafür gibt es jetzt den Collider
