### ISSUE TITLE
TA4 Matrix Screen Programmer

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage_feature_requests#57]
Dein Matrix-Screen mit dem Programmer sind sehr gelungene Teile aber, kann man den Programmer noch um ein paar Kleinigkeiten erweitern:

Setzen einer Stift-Farbe mit der weitere Figuren gemalt werden können.
Da denke ich an

Linie mit Angabe der Länge.
Kreis mit Angabe des Radius.
Quadrat mit Angabe der Seitenlänge.
Dreieck mit Angabe der der Schenkellänge.
Löschen mit der angegebenen Stiftfarbe.

Das würde die Handhabung deines Werkzeuges immens erleichtern.

Gruß, Clyde.

**Comment by acmgit** [comment]
Und ich weiß, aber ich komme ins Träumen wenn diese Tafeln sogar programmierbar wären. Ich sehe schon Laufschriften die butterrweich scrollen, Uhren die die Weltzeit in Echtzeit anzeigen könnten, echtes Las Vegas in Minetest  ....

Gruß, Clyde.

**Comment by joe7575** [comment]
Diese TA Erweitertung ist nicht von mir. Die ist von Thomas (https://github.com/Thomas--S/ta4_addons)
Er hatte am Anfang mehr Features, aber das war nicht servertauglich (zu viel lags wegen hohem Netzwerkverkehr).
Im Singleplayer sicher eine feine Sache.

**Comment by acmgit** [comment]
Oh, vielen Dank für die Info, werde mal mit Thomas sprechen.
Ich habe sie bei mir auf Zeitsprung im Einsatz, sie erzeugt bei mir keine lags.
Wenn die Tafel selbst scrolling anbieten soll, dann wird es auf dem Server sicher zeitkritisch.
Gruß, Clyde.
