### ISSUE TITLE
Durchflussanzeigesensor

### ISSUE THREAD

**Issue by anju1864** [joe7575/techage_feature_requests#60]
Einen Durchflussanzeigesensor wie der TA3 Leitungs/Wanddurchbruch nur als Leuchtelement grün bei Durchfluss.

**Comment by joe7575** [comment]
so wie der TA3/TA4 Detektor?

**Comment by anju1864** [comment]
Ja wie der so in der Art eben für Flüssigkeiten. Und das er bei durchfluss leuchtet.

**Comment by joe7575** [comment]
Das geht leider nicht so einfach. Bei Flüssigkeiten gibt es nur tanks und pipes und logische Verbindungen dazwischen, die mit Hilfe der Röhrenblöcke berechnet werden Zu Laufzeit "fließt" da nichts durch die Röhren. 

Dies war bei der Idee des Durchflußbegrenzers schon nicht machbar
