### ISSUE TITLE
Mengenbegrenzer

### ISSUE THREAD

**Issue by anju1864** [joe7575/techage_feature_requests#61]
Einen Mengenbegrenzer  den man anklickt und einen Numerischen Wert eingibt. Diesen kann man über den Lua Controller mit "state" abfragen und als Variable weiterverarbeiten.

**Comment by joe7575** [comment]
- Was soll der begrenzen? Items oder Liquids?
- Wenn die Menge erreicht wird, soll der dann auf "blocking" schalten?
- Was soll der als state liefern? on/off?
- soll der auch die Menge liefern, die durchgeleitet wurde?
- Muss man den zurücksetzen können?

**Comment by anju1864** [comment]
1. wäre schon praktisch 1x Flüssig 1x Items also 2 Verschiedene.
2. state würde on/off ok
3. Menge ja ist ein muss, damit man über Lua auf die Menge zugreifen kann.
4. Zurücksetzen ja.

Also im Prinzip  er sitzt vor einem Tank bzw. einem anderen Aktor. Ich stelle ihn auf 200 l bzw. 50 Stck. ein und wenn diese Menge erreicht ist wertet das Script im LUA Controller das off aus und sendet an die Pumpe, Ventil oder Schieber ein off.
Bei bedarf kann man dan den Mengenbegrenzer mit on wieder starten bzw. setzt ein anderes Limit.

**Comment by joe7575** [comment]
Ich mach den mal zu. Es gibt zwar keine Mengenbegrenzer für Items und Flüssigkeiten, aber TA4 Pumpe und Schieber können jetzt entsprechend konfiguriert werden, so dass nur die angegebene Menge transportiert wird.
